# Generated by Django 5.2.17 on 2026-10-01 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0001_initial'),
        ('catalogo', '0003_variante'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcarrito',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items_carrito', to='catalogo.variante'),
        ),
        migrations.AddField(
            model_name='lineapedido',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineas_pedido', to='catalogo.variante'),
        ),
    ]
