# Generated by Django 5.2.17 on 2026-09-26 19:09

import devconfsite.catalogo.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'categoría',
                'verbose_name_plural': 'categorías',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('image', models.CharField(max_length=500, validators=[django.core.validators.RegexValidator(message='Enter an image URL starting with https:// (or a path of this site, like /images/catalog/photo.png).', regex='^(https://\\S+|/(?!/)\\S*)$')])),
                ('is_new', models.BooleanField(default=False)),
                ('recommended', models.BooleanField(default=False)),
                ('options', models.JSONField(blank=True, default=list, validators=[devconfsite.catalogo.models.validate_options])),
                ('status', models.CharField(choices=[('live', 'Live'), ('disabled', 'Disabled')], default='live', max_length=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='catalogo.categoria')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'recommended'], name='catalogo_pr_status_7a4275_idx'), models.Index(fields=['category', 'status'], name='catalogo_pr_categor_00a167_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='precio_no_negativo')],
            },
        ),
    ]
