# Generated by Django 5.2.17 on 2026-10-01 21:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_producto_search_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.JSONField(default=list)),
                ('options_key', models.CharField(editable=False, max_length=500)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock', models.PositiveIntegerField(default=0)),
                ('sku', models.CharField(blank=True, default='', max_length=60)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalogo.producto')),
            ],
            options={
                'verbose_name': 'variante',
                'verbose_name_plural': 'variantes',
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('product', 'options_key'), name='variante_unica_por_producto'), models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='precio_variante_no_negativo')],
            },
        ),
    ]
